version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.4

jobs:
  build:
    parallelism: 6
    docker:
      - image: cimg/node:20.0.0-browsers
    working_directory: ~/script-runner
    steps:  # This is required to define the steps within the command
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build Project
          command: NODE_OPTIONS="--max-old-space-size=4096" bash ./ci/build.sh
      ## persist the build
      - persist_to_workspace:
          root: .
          paths:
            - ./dist/projects

  test:
    parallelism: 10
    docker:
      - image: cimg/node:20.0.0-browsers
    working_directory: ~/script-runner
    steps:
      - checkout
        - attach_workspace:
            at: .
      - run: 
          name: check files
          command: find build/projects
      - browser-tools/install-browser-tools:
          install-firefox: false
          install-chrome: true
          install-chromedriver: false
          install-geckodriver: false
      - store_test_results:
          path: ./test/reports/tests
      - store_artifacts:
          path: ./test/reports/screenshots

  deploy:
    docker:
      - image: cimg/node:20.0.0-browsers
    working_directory: ~/script-runner
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            ./ci/deploy.sh
workflows:
  version: 2
  main_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
